apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studentapp-ingress
  labels:
    app: studentapp
spec:
  ingressClassName: nginx
  rules:
  - host:  a128f391569fd40aa800a2302d25c9da-1440730611.ap-south-1.elb.amazonaws.com  
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service: 
            name: studentapp-svc
            port: 
              number: 8080

      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: studentapp-frontend-svc
            port: 
              number: 80